import { test, expect, type ElectronApplication, type Page } from '@playwright/test';
import { launchApp, closeApp } from './electron';

let app: ElectronApplication;
let page: Page;

test.beforeAll(async () => {
  ({ app, page } = await launchApp());
});

test.afterAll(async () => {
  await closeApp(app);
});

// ---------------------------------------------------------------------------
// Global Search
// ---------------------------------------------------------------------------

test.describe('Global Search', () => {
  test('should display the global search input', async () => {
    await expect(page.getByTestId('ants-global-search')).toBeVisible();
  });

  test('should accept keyboard input', async () => {
    const searchInput = page.getByTestId('ants-global-search');
    // Use force click because the title bar drag region intercepts pointer events
    // on intermediate wrapper divs generated by react-native-web
    await searchInput.click({ force: true });
    await searchInput.fill('test query');
    // Verify the input accepted the text
    await expect(searchInput).toHaveValue('test query');
    // Clear it for cleanup
    await searchInput.fill('');
  });
});
