#!/usr/bin/env npx tsx
/**
 * Generate platform-specific E2E tests from shared scenario YAML files.
 *
 * Reads scenarios from ../scenarios/*.yaml and produces:
 *   - Playwright specs in ../../desktop/e2e/generated/<name>.spec.ts
 *   - Maestro flows in ../../mobile/maestro/flows/generated/<name>.yaml
 *
 * Usage:
 *   npx tsx src/generate.ts           # Generate files
 *   npx tsx src/generate.ts --check   # Check if generated files are up-to-date
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';
import { load } from 'js-yaml';
import type {
  Scenario,
  Step,
} from './types.js';
import {
  isTapStep,
  isTypeStep,
  isAssertVisibleStep,
  isWaitStep,
  getAction,
} from './types.js';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname, '..');
const SCENARIOS_DIR = join(ROOT, 'scenarios');
const PLAYWRIGHT_OUT = resolve(ROOT, '..', '..', 'apps', 'desktop', 'e2e', 'generated');
const MAESTRO_OUT = resolve(ROOT, '..', '..', 'apps', 'mobile', 'maestro', 'flows', 'generated');

// ---------------------------------------------------------------------------
// Load scenarios
// ---------------------------------------------------------------------------

function loadScenarios(): { name: string; scenario: Scenario }[] {
  const files = readdirSync(SCENARIOS_DIR).filter((f) => f.endsWith('.yaml'));
  return files.map((file) => {
    const content = readFileSync(join(SCENARIOS_DIR, file), 'utf-8');
    const scenario = load(content) as Scenario;
    return { name: basename(file, '.yaml'), scenario };
  });
}

// ---------------------------------------------------------------------------
// Filter steps by platform
// ---------------------------------------------------------------------------

function desktopSteps(steps: Step[]): Step[] {
  return steps.filter((s) => {
    const action = getAction(s);
    // Exclude steps explicitly tagged as mobile-only
    return !(action.mobile === true && !action.desktop);
  });
}

function mobileSteps(steps: Step[]): Step[] {
  return steps.filter((s) => {
    const action = getAction(s);
    // Exclude steps explicitly tagged as desktop-only
    return !(action.desktop === true && !action.mobile);
  });
}

// ---------------------------------------------------------------------------
// Generate Playwright spec
// ---------------------------------------------------------------------------

function generatePlaywrightSpec(name: string, scenario: Scenario): string {
  const steps = desktopSteps(scenario.steps);
  const lines: string[] = [];

  lines.push(`// AUTO-GENERATED by @openmgr/test-scenarios — do not edit manually`);
  lines.push(`// Source: scenarios/${name}.yaml`);
  lines.push(``);
  lines.push(`import { test, expect, type ElectronApplication, type Page } from '@playwright/test';`);
  lines.push(`import { launchApp, closeApp } from '../electron';`);
  lines.push(``);
  lines.push(`let app: ElectronApplication;`);
  lines.push(`let page: Page;`);
  lines.push(``);
  lines.push(`test.beforeAll(async () => {`);
  lines.push(`  ({ app, page } = await launchApp());`);
  lines.push(`});`);
  lines.push(``);
  lines.push(`test.afterAll(async () => {`);
  lines.push(`  await closeApp(app);`);
  lines.push(`});`);
  lines.push(``);
  // Check if scenario has preconditions that require app state (e.g., an
  // existing project).  In CI the app starts with a clean slate so these
  // preconditions cannot be met — emit a runtime test.skip().
  const requiresProject = scenario.preconditions?.some(p => p.projectExists);

  lines.push(`test.describe('${scenario.name}', () => {`);
  lines.push(`  test('${scenario.description}', async () => {`);

  if (requiresProject) {
    lines.push(`    // Skip when no project exists (clean CI environment)`);
    lines.push(`    const welcomeScreen = page.getByTestId('openmgr-welcome-screen');`);
    lines.push(`    const hasWelcome = await welcomeScreen.isVisible().catch(() => false);`);
    lines.push(`    test.skip(hasWelcome, 'Requires an existing project — welcome screen is showing');`);
  }

  for (const step of steps) {
    if (isTapStep(step)) {
      const { testId, text } = step.tap;
      if (testId) {
        lines.push(`    await page.getByTestId('${testId}').click();`);
      } else if (text) {
        lines.push(`    await page.getByText('${text}').click();`);
      }
    } else if (isTypeStep(step)) {
      const { testId, text } = step.type;
      if (testId) {
        lines.push(`    await page.getByTestId('${testId}').fill('${text}');`);
      } else {
        lines.push(`    await page.keyboard.type('${text}');`);
      }
    } else if (isAssertVisibleStep(step)) {
      const { testId, text } = step.assertVisible;
      if (testId) {
        lines.push(`    await expect(page.getByTestId('${testId}')).toBeVisible();`);
      } else if (text) {
        lines.push(`    await expect(page.getByText('${text}')).toBeVisible();`);
      }
    } else if (isWaitStep(step)) {
      const { testId, text } = step.waitForVisible;
      if (testId) {
        lines.push(`    await expect(page.getByTestId('${testId}')).toBeVisible({ timeout: 10000 });`);
      } else if (text) {
        lines.push(`    await expect(page.getByText('${text}')).toBeVisible({ timeout: 10000 });`);
      }
    }
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Generate Maestro flow
// ---------------------------------------------------------------------------

function generateMaestroFlow(name: string, scenario: Scenario): string {
  const steps = mobileSteps(scenario.steps);
  const lines: string[] = [];

  lines.push(`# AUTO-GENERATED by @openmgr/test-scenarios — do not edit manually`);
  lines.push(`# Source: scenarios/${name}.yaml`);
  lines.push(`# ${scenario.name}: ${scenario.description}`);
  lines.push(`appId: dev.openmgr.app`);
  lines.push(`---`);
  lines.push(`- launchApp`);

  for (const step of steps) {
    if (isTapStep(step)) {
      const { testId, text } = step.tap;
      if (testId) {
        lines.push(`- tapOn:`);
        lines.push(`    id: "${testId}"`);
      } else if (text) {
        lines.push(`- tapOn:`);
        lines.push(`    text: "${text}"`);
      }
    } else if (isTypeStep(step)) {
      const { testId, text } = step.type;
      if (testId) {
        lines.push(`- tapOn:`);
        lines.push(`    id: "${testId}"`);
      }
      lines.push(`- inputText: "${text}"`);
    } else if (isAssertVisibleStep(step)) {
      const { testId, text } = step.assertVisible;
      if (testId) {
        lines.push(`- assertVisible:`);
        lines.push(`    id: "${testId}"`);
      } else if (text) {
        lines.push(`- assertVisible:`);
        lines.push(`    text: "${text}"`);
      }
    } else if (isWaitStep(step)) {
      const { testId, text } = step.waitForVisible;
      if (testId) {
        lines.push(`- assertVisible:`);
        lines.push(`    id: "${testId}"`);
      } else if (text) {
        lines.push(`- assertVisible:`);
        lines.push(`    text: "${text}"`);
      }
    }
  }

  lines.push(``);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const checkMode = process.argv.includes('--check');
  const scenarios = loadScenarios();

  if (scenarios.length === 0) {
    console.log('No scenarios found in', SCENARIOS_DIR);
    return;
  }

  // Ensure output directories exist
  if (!checkMode) {
    mkdirSync(PLAYWRIGHT_OUT, { recursive: true });
    mkdirSync(MAESTRO_OUT, { recursive: true });
  }

  let allUpToDate = true;

  for (const { name, scenario } of scenarios) {
    const playwrightSpec = generatePlaywrightSpec(name, scenario);
    const maestroFlow = generateMaestroFlow(name, scenario);

    const playwrightPath = join(PLAYWRIGHT_OUT, `${name}.spec.ts`);
    const maestroPath = join(MAESTRO_OUT, `${name}.yaml`);

    if (checkMode) {
      // Check mode: compare with existing files
      const existingPlaywright = existsSync(playwrightPath)
        ? readFileSync(playwrightPath, 'utf-8')
        : null;
      const existingMaestro = existsSync(maestroPath)
        ? readFileSync(maestroPath, 'utf-8')
        : null;

      if (existingPlaywright !== playwrightSpec) {
        console.log(`OUT OF DATE: ${playwrightPath}`);
        allUpToDate = false;
      }
      if (existingMaestro !== maestroFlow) {
        console.log(`OUT OF DATE: ${maestroPath}`);
        allUpToDate = false;
      }
    } else {
      // Generate mode: write files
      writeFileSync(playwrightPath, playwrightSpec, 'utf-8');
      console.log(`  Playwright: ${playwrightPath}`);
      writeFileSync(maestroPath, maestroFlow, 'utf-8');
      console.log(`  Maestro:    ${maestroPath}`);
    }
  }

  if (checkMode) {
    if (allUpToDate) {
      console.log('All generated files are up-to-date.');
    } else {
      console.error('\nGenerated files are out of date. Run: pnpm --filter @openmgr/test-scenarios generate');
      process.exit(1);
    }
  } else {
    console.log(`\nGenerated tests from ${scenarios.length} scenarios.`);
  }
}

main();
