/**
 * Icon imports for React Native (lucide-react-native).
 * This file is used when bundling for native platforms.
 * For web, see icons.tsx
 */
import {
  X,
  Plus,
  Minus,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  Send,
  Paperclip,
  Settings,
  Trash2,
  Pencil,
  Menu,
  Search,
  MoreHorizontal,
  Copy,
  Files,
  MessageSquare,
  Folder,
  FolderOpen,
  File,
  Terminal,
  Play,
  Square,
  RefreshCw,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Loader2,
  ExternalLink,
  Link,
  Unlink,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  User,
  Users,
  Globe,
  Server,
  Database,
  Code,
  GitBranch,
  Zap,
  Sun,
  Moon,
  Monitor,
  Laptop,
  Key,
  Shield,
  PanelRight,
  PanelRightClose,
  PanelLeft,
  PanelLeftClose,
  Wrench,
  Hammer,
  CircleQuestionMark,
  Sparkles,
  type LucideIcon,
} from 'lucide-react-native';

export type IconComponent = LucideIcon;

// Map icon names to Lucide components
export const iconMap: Record<string, IconComponent> = {
  close: X,
  x: X,
  plus: Plus,
  add: Plus,
  minus: Minus,
  check: Check,
  'chevron-right': ChevronRight,
  chevronRight: ChevronRight,
  'chevron-left': ChevronLeft,
  chevronLeft: ChevronLeft,
  'chevron-down': ChevronDown,
  chevronDown: ChevronDown,
  'chevron-up': ChevronUp,
  chevronUp: ChevronUp,
  'arrow-left': ArrowLeft,
  arrowLeft: ArrowLeft,
  back: ArrowLeft,
  'arrow-right': ArrowRight,
  arrowRight: ArrowRight,
  forward: ArrowRight,
  send: Send,
  attach: Paperclip,
  paperclip: Paperclip,
  settings: Settings,
  gear: Settings,
  trash: Trash2,
  delete: Trash2,
  edit: Pencil,
  pencil: Pencil,
  menu: Menu,
  hamburger: Menu,
  search: Search,
  more: MoreHorizontal,
  moreHorizontal: MoreHorizontal,
  copy: Copy,
  duplicate: Files,
  files: Files,
  message: MessageSquare,
  chat: MessageSquare,
  folder: Folder,
  folderOpen: FolderOpen,
  file: File,
  terminal: Terminal,
  play: Play,
  stop: Square,
  refresh: RefreshCw,
  reload: RefreshCw,
  alertCircle: AlertCircle,
  warning: AlertCircle,
  info: Info,
  checkCircle: CheckCircle,
  success: CheckCircle,
  xCircle: XCircle,
  error: XCircle,
  loader: Loader2,
  loading: Loader2,
  externalLink: ExternalLink,
  link: Link,
  unlink: Unlink,
  eye: Eye,
  show: Eye,
  eyeOff: EyeOff,
  hide: EyeOff,
  lock: Lock,
  unlock: Unlock,
  user: User,
  users: Users,
  globe: Globe,
  server: Server,
  database: Database,
  code: Code,
  git: GitBranch,
  gitBranch: GitBranch,
  zap: Zap,
  lightning: Zap,
  sun: Sun,
  light: Sun,
  moon: Moon,
  dark: Moon,
  monitor: Monitor,
  system: Monitor,
  laptop: Laptop,
  computer: Laptop,
  key: Key,
  apiKey: Key,
  shield: Shield,
  security: Shield,
  panelRight: PanelRight,
  panelRightClose: PanelRightClose,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
  sidebarRight: PanelRight,
  sidebarRightClose: PanelRightClose,
  sidebarLeft: PanelLeft,
  sidebarLeftClose: PanelLeftClose,
  wrench: Wrench,
  tool: Wrench,
  hammer: Hammer,
  build: Hammer,
  circleQuestionMark: CircleQuestionMark,
  helpCircle: CircleQuestionMark,
  question: CircleQuestionMark,
  sparkles: Sparkles,
};
